name: Lint, Type Check, and Test

on: [push, pull_request]

jobs:
  qol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Lint
        run: |
          pip install ruff
          ruff check .
      - name: Type check
        run: |
          pip install pyright
          poetry run pyright
      - name: Test
        run: |
          pip install pytest
          PYTHONPATH=$PYTHONPATH:. poetry run pytype