name: Lint, Type Check, and Test

on: [push, pull_request]

jobs:
  qol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Lint
        run: |
          pip install ruff
          make lint
      - name: Type check
        run: |
          pip install pyright
          make type-check
      - name: Test
        run: |
          pip install pytest
          make test